<a href="https://colab.research.google.com/github/NjoodJ/Training/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [12]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print('For first sent', onehot_repr[0])
print('For all sent', onehot_repr)

For first sent [2115, 6964, 3281, 4090]
For all sent [[2115, 6964, 3281, 4090], [2115, 6964, 3281, 4396], [2115, 1246, 3281, 9641], [8597, 2710, 6258, 8674, 6903], [8597, 2710, 6258, 8674, 4376], [9096, 2115, 4560, 3281, 5655], [946, 6185, 452, 8674]]


In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [29]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[2115 6964 3281 4090    0    0    0    0    0    0]
 [2115 6964 3281 4396    0    0    0    0    0    0]
 [2115 1246 3281 9641    0    0    0    0    0    0]
 [8597 2710 6258 8674 6903    0    0    0    0    0]
 [8597 2710 6258 8674 4376    0    0    0    0    0]
 [9096 2115 4560 3281 5655    0    0    0    0    0]
 [ 946 6185  452 8674    0    0    0    0    0    0]]


In [30]:
#Number of features in array
dim=10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 10, 10)            100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

In [35]:
embedded_docs[3]

array([8597, 2710, 6258, 8674, 6903,    0,    0,    0,    0,    0],
      dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])